#!/usr/bin/env python3
# TODO: Add Apache license header
"""
Command-line tool for managing per-tenant PostgreSQL users.

Usage:
    # Generate SQL for a new tenant
    python manage_tenant_users.py generate-sql demo --password "secure123"

    # Create a tenant user directly (requires admin connection)
    python manage_tenant_users.py create demo --password "secure123" --db-uri "postgresql://admin:pass@host/db"

    # Verify isolation between tenants
    python manage_tenant_users.py verify demo acme --db-uri "postgresql://admin:pass@host/db"

    # Update tenant credentials in Superset
    python manage_tenant_users.py update-tenant demo --password "secure123"
"""

import argparse
import secrets
import string
import sys
from typing import Optional


def generate_password(length: int = 32) -> str:
    """Generate a secure random password."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_sql(tenant_id: str, password: str, database: str = "your_database") -> str:
    """Generate SQL for creating a tenant user."""
    username = f"tenant_{tenant_id}_user"
    schema = f"tenant_{tenant_id}"

    return f"""-- Per-Tenant User Setup for: {tenant_id}
-- Generated by manage_tenant_users.py
-- Run as PostgreSQL superuser

-- 1. Create schema if not exists
CREATE SCHEMA IF NOT EXISTS {schema};

-- 2. Create tenant user
CREATE USER {username} WITH PASSWORD '{password}';

-- 3. Revoke default public access
REVOKE ALL ON SCHEMA public FROM {username};

-- 4. Grant database connect
GRANT CONNECT ON DATABASE {database} TO {username};

-- 5. Grant schema access (ONLY to this tenant's schema)
GRANT USAGE ON SCHEMA {schema} TO {username};
GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO {username};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA {schema} TO {username};

-- 6. Default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA {schema}
    GRANT SELECT ON TABLES TO {username};

-- 7. Verify isolation (run manually to test)
-- SET ROLE {username};
-- SELECT * FROM {schema}.some_table LIMIT 1;  -- Should work
-- SELECT * FROM public.some_table LIMIT 1;    -- Should fail: permission denied
-- SELECT * FROM tenant_other.some_table LIMIT 1;  -- Should fail: permission denied
-- RESET ROLE;

-- =============================================================================
-- After running this SQL, update the tenant in Superset:
--
-- From Python:
--   tenant = Tenant.query.filter_by(tenant_id='{tenant_id}').first()
--   tenant.warehouse_db_user = '{username}'
--   tenant.set_warehouse_password('{password}')
--   db.session.commit()
--
-- Or use the admin UI to update warehouse credentials.
-- =============================================================================
"""


def create_user_direct(
    tenant_id: str,
    password: str,
    db_uri: str,
) -> bool:
    """Create tenant user directly in the database."""
    try:
        from sqlalchemy import create_engine, text

        engine = create_engine(db_uri)
        username = f"tenant_{tenant_id}_user"
        schema = f"tenant_{tenant_id}"
        database = engine.url.database

        with engine.connect() as conn:
            # Create schema
            conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema}"))

            # Create user
            conn.execute(text(
                f"CREATE USER {username} WITH PASSWORD :password"
            ), {"password": password})

            # Revoke public
            conn.execute(text(f"REVOKE ALL ON SCHEMA public FROM {username}"))

            # Grant connect
            conn.execute(text(
                f"GRANT CONNECT ON DATABASE {database} TO {username}"
            ))

            # Grant schema access
            conn.execute(text(f"GRANT USAGE ON SCHEMA {schema} TO {username}"))
            conn.execute(text(
                f"GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO {username}"
            ))

            # Default privileges
            conn.execute(text(
                f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} "
                f"GRANT SELECT ON TABLES TO {username}"
            ))

            conn.commit()

        print(f"Created user {username} with access to {schema}")
        return True

    except Exception as e:
        print(f"Error creating user: {e}", file=sys.stderr)
        return False


def verify_isolation(
    tenant1_id: str,
    tenant2_id: str,
    db_uri: str,
) -> bool:
    """Verify that tenant1 cannot access tenant2's schema."""
    try:
        from sqlalchemy import create_engine, text

        engine = create_engine(db_uri)

        with engine.connect() as conn:
            user1 = f"tenant_{tenant1_id}_user"
            schema2 = f"tenant_{tenant2_id}"

            # Switch to tenant1's role
            conn.execute(text(f"SET ROLE {user1}"))

            # Try to access tenant2's schema
            try:
                conn.execute(text(f"SELECT 1 FROM {schema2}.dummy_table"))
                print(f"SECURITY FAILURE: {user1} CAN access {schema2}!")
                return False
            except Exception as e:
                if "permission denied" in str(e).lower():
                    print(f"Isolation verified: {user1} cannot access {schema2}")
                    return True
                print(f"Inconclusive: {e}")
                return False
            finally:
                conn.execute(text("RESET ROLE"))

    except Exception as e:
        print(f"Error verifying isolation: {e}", file=sys.stderr)
        return False


def update_tenant_credentials(
    tenant_id: str,
    password: str,
    flask_app_context: bool = False,
) -> bool:
    """Update tenant's warehouse credentials in Superset."""
    try:
        if flask_app_context:
            from keycloak_multi_tenant.models import Tenant
            from superset import db

            tenant = Tenant.query.filter_by(tenant_id=tenant_id).first()
            if not tenant:
                print(f"Tenant not found: {tenant_id}", file=sys.stderr)
                return False

            tenant.warehouse_db_user = f"tenant_{tenant_id}_user"
            tenant.set_warehouse_password(password)
            db.session.commit()

            print(f"Updated warehouse credentials for tenant: {tenant_id}")
            return True
        else:
            print(
                "To update tenant credentials, run this within Flask context:\n"
                "\n"
                "  flask shell\n"
                f"  >>> from keycloak_multi_tenant.models import Tenant\n"
                f"  >>> from superset import db\n"
                f"  >>> tenant = Tenant.query.filter_by(tenant_id='{tenant_id}').first()\n"
                f"  >>> tenant.warehouse_db_user = 'tenant_{tenant_id}_user'\n"
                f"  >>> tenant.set_warehouse_password('{password}')\n"
                f"  >>> db.session.commit()\n"
            )
            return True

    except Exception as e:
        print(f"Error updating tenant: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Manage per-tenant PostgreSQL users for secure isolation"
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # generate-sql command
    gen_parser = subparsers.add_parser(
        "generate-sql",
        help="Generate SQL for creating a tenant user"
    )
    gen_parser.add_argument("tenant_id", help="Tenant identifier (e.g., 'demo')")
    gen_parser.add_argument(
        "--password", "-p",
        help="Password for the user (auto-generated if not provided)"
    )
    gen_parser.add_argument(
        "--database", "-d",
        default="your_database",
        help="Database name"
    )

    # create command
    create_parser = subparsers.add_parser(
        "create",
        help="Create a tenant user directly in the database"
    )
    create_parser.add_argument("tenant_id", help="Tenant identifier")
    create_parser.add_argument(
        "--password", "-p",
        help="Password for the user (auto-generated if not provided)"
    )
    create_parser.add_argument(
        "--db-uri",
        required=True,
        help="PostgreSQL admin connection URI"
    )

    # verify command
    verify_parser = subparsers.add_parser(
        "verify",
        help="Verify isolation between two tenants"
    )
    verify_parser.add_argument("tenant1_id", help="First tenant identifier")
    verify_parser.add_argument("tenant2_id", help="Second tenant identifier")
    verify_parser.add_argument(
        "--db-uri",
        required=True,
        help="PostgreSQL admin connection URI"
    )

    # update-tenant command
    update_parser = subparsers.add_parser(
        "update-tenant",
        help="Update tenant's warehouse credentials in Superset"
    )
    update_parser.add_argument("tenant_id", help="Tenant identifier")
    update_parser.add_argument(
        "--password", "-p",
        required=True,
        help="Password for the warehouse user"
    )

    args = parser.parse_args()

    if args.command == "generate-sql":
        password = args.password or generate_password()
        sql = generate_sql(args.tenant_id, password, args.database)
        print(sql)
        if not args.password:
            print(f"\n# Generated password: {password}", file=sys.stderr)

    elif args.command == "create":
        password = args.password or generate_password()
        if create_user_direct(args.tenant_id, password, args.db_uri):
            print(f"\n# Password: {password}")
        else:
            sys.exit(1)

    elif args.command == "verify":
        if not verify_isolation(args.tenant1_id, args.tenant2_id, args.db_uri):
            sys.exit(1)

    elif args.command == "update-tenant":
        update_tenant_credentials(args.tenant_id, args.password)

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
